-- MySQL Script generated by MySQL Workbench
-- Wed Mar  9 17:29:37 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema builder_shop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema builder_shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `builder_shop` DEFAULT CHARACTER SET utf8 ;
USE `builder_shop` ;

-- -----------------------------------------------------
-- Table `builder_shop`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `builder_shop`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(90) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `builder_shop`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `builder_shop`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  `image` LONGBLOB NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `builder_shop`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `builder_shop`.`item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `image` LONGBLOB NOT NULL,
  `price` INT NOT NULL,
  `description` VARCHAR(255) NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_item_category_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_item_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `builder_shop`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `builder_shop`.`shopping_cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `builder_shop`.`shopping_cart` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_shopping_cart_user1_idx` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_shopping_cart_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `builder_shop`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `builder_shop`.`shopping_cart_has_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `builder_shop`.`shopping_cart_has_item` (
  `shopping_cart_id` INT NOT NULL,
  `item_item_id` INT NOT NULL,
  PRIMARY KEY (`shopping_cart_id`, `item_item_id`),
  INDEX `fk_shopping_cart_has_item_item1_idx` (`item_item_id` ASC) VISIBLE,
  INDEX `fk_shopping_cart_has_item_shopping_cart1_idx` (`shopping_cart_id` ASC) VISIBLE,
  CONSTRAINT `fk_shopping_cart_has_item_shopping_cart1`
    FOREIGN KEY (`shopping_cart_id`)
    REFERENCES `builder_shop`.`shopping_cart` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shopping_cart_has_item_item1`
    FOREIGN KEY (`item_item_id`)
    REFERENCES `builder_shop`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `builder_shop`.`order_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `builder_shop`.`order_history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `sum` INT NOT NULL,
  `transaction_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_history_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_history_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `builder_shop`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `builder_shop`.`order_history_has_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `builder_shop`.`order_history_has_item` (
  `order_history_id` INT NOT NULL,
  `item_item_id` INT NOT NULL,
  `count` INT NOT NULL,
  PRIMARY KEY (`order_history_id`, `item_item_id`),
  INDEX `fk_order_history_has_item_item1_idx` (`item_item_id` ASC) VISIBLE,
  INDEX `fk_order_history_has_item_order_history1_idx` (`order_history_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_history_has_item_order_history1`
    FOREIGN KEY (`order_history_id`)
    REFERENCES `builder_shop`.`order_history` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_history_has_item_item1`
    FOREIGN KEY (`item_item_id`)
    REFERENCES `builder_shop`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
